apiVersion: v1
kind: Service
metadata:
  name: cloud-eureka
  labels:
    app: cloud-eureka
  namespace: micro-cloud
spec:
  type: NodePort
  ports:
  - port: 10110
    nodePort: 20110
  selector:
    app: cloud-eureka